sudo: false
language: java
install: ./gradlew --quiet install
script: mvn --quiet verify
jdk:
  - oraclejdk8
notifications:
  email:
      - toni.menzel@rebaze.com
  slack: rebaze:W2NAFBrzwufg7HptbqgE3hgB
